### ISSUE TITLE
Add a timeline

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#1]
With project and organizational logos; also with pre-CWL major events like Taverna's SCUFL: https://www.slideshare.net/soilandreyes/2011-0706-scufl2-poster-because-a-workflow-is-more-than-its-definition-bosc-2011

**Comment by swzCuroverse** [comment]
@mr-c can you give me some more information about what should go here?

**Comment by mr-c** [comment]
Like https://docs.google.com/presentation/d/1CqrimuWb8BiMe39BzTmAlAzycI5Zd4Ttl-OwAkM-3D4/edit#slide=id.g704f93e16c_0_219 but more entries + links for more information

**Comment by swzCuroverse** [comment]
great thanks!

**Comment by swzCuroverse** [comment]
2014 Bioinformatics Open Source Conference CodeFest:
4 software engineers & a whiteboard
2015: CWL “draft-2” version, commercial vendor (SBG) releases product in December.
2016: CWL v1.0 released
2017: CWL v1.0.1 and v1.0.2 released.
	Now 4 public implementations
2018: IBM released their CWL implementation for LSF.
2019: CWL v1.1 released
2020: CWL v1.2 released with workflow conditionals, work on CWL v1.2.1 and beyond commences

**Comment by swzCuroverse** [comment]
This is in the new version of the website -- Can we close this out, @mr-c and @lunacodes ?

**Comment by mr-c** [comment]
Thanks!
