### ISSUE TITLE
No link to Common Workflow Language Lab

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/cwl-website#103]
It would be nice if there is a link to [Common Workflow Language Lab](https://github.com/common-workflow-lab).
It is very helpful but currently I cannot find a link to CWL Lab from the official website.

**Comment by mr-c** [comment]
@tom-tan That's a good idea, thank you! On which page and in which section would you expect to find it?

**Comment by tom-tan** [comment]
IMO [Development Tools](https://www.commonwl.org/tools/) page is an appropriate place for it.
For example, we can add a sentence as follows:
```md
Beyond releasing the CWL standards, ... for popular tools.
(Added) Other tools are also available in [Common Workflow Language Lab](https://github.com/common-workflow-lab).
```
