### ISSUE TITLE
bottom of users gallery: add instructions on how to request an addition

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#107]
We can make an issue template here. I think that would be the easiest way

**Comment by lunacodes** [comment]
I see that you made the [issue template](https://github.com/common-workflow-language/cwl-website/blob/main/.github/ISSUE_TEMPLATE/user-gallery-nomination.md). I'll add a mention of it to the README.md (which I'm working on currently), this coming week.

**Comment by lunacodes** [comment]
Note: This is being added in #125
