### ISSUE TITLE
Documenting the CWL Technical Team

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#112]
- [x] Need to create a new section under https://www.commonwl.org/governance/ named "CWL Technical Team"
        The team is initially responsible for approving new versions of the CWL standards before that proposal goes to the CWL Leadership Team for the final vote.
- [x] Collect ORCIDs as well

Confirmed members who have consented to being listed:

- Name: Iacopo Colonnelli
  Affiliation: University of Torino, Computer Science Dept.
  GitHub: https://github.com/glassofwhiskey
  Matrix: https://matrix.to/#/@glassofwhiskey:matrix.org
  ORCID: https://orcid.org/0000-0001-9290-2017
- Name: Michael R. Crusoe
  Affiliation: ELIXIR-NL
  GitHub: https://github.com/mr-c 
  Matrix: https://matrix.to/#/@mr-c:matrix.org
  ORCID: https://orcid.org/0000-0002-2961-9670
- Name: Stian Soiland-Reyes
  Affilitaion: eScience Lab, The University of Manchester
  GitHub: https://github.com/stain 
  Matrix: n/a
  ORCID: https://orcid.org/0000-0001-9842-9718
- Name: Fabrice Brito
  Affiliation: Terradue 
  GitHub: https://github.com/fabricebrito 
  Matrix: https://matrix.to/#/@fabrito:matrix.org
  ORCID: ???
- Name: Tomoya Tanjo
  Affiliation: Bioinformation and DDBJ Center, National Institute of Genetics
  GitHub: https://github.com/tom-tan
  Matrix: https://matrix.to/#/@tom-tan:matrix.org
  ORCID: https://orcid.org/0000-0002-4421-9659
- Name: Bogdan Gavrilović
  Affiliation: Seven Bridges
  GitHub: https://github.com/bogdang989
  Matrix: https://matrix.to/#/@bogdan_gavrilovic:matrix.org
  ORCID: https://orcid.org/0000-0003-1550-1716
- Name: Peter Amstutz
  Affiliation: Curii Corporation / Arvados
  GitHub: https://github.com/tetron
  Matrix: https://matrix.to/#/@tetron:matrix.org
  ORCID: https://orcid.org/0000-0003-3566-7705
- Name: Lon Blauvelt
  Affiliation: University of California Santa Cruz / Toil Project
  GitHub: https://github.com/DailyDreaming
  Matrix: https://matrix.to/#/@dailydreaming:matrix.org
  ORCID: https://orcid.org/0000-0001-8352-873X
- Name: Manabu Ishii
  Affiliation: Genome Analytics Japan Inc.
  GitHub: https://github.com/manabuishii
  Matrix:  https://matrix.to/#/@manabuishii:matrix.org
  ORCID: https://orcid.org/0000-0002-5843-4712
- Name: Marius van den Beek
  Affiliation: Galaxy Project
  GitHub: https://github.com/mvdbeek
  Matrix: https://matrix.to/#/@mvdbeek:matrix.org
  ORCID: https://orcid.org/0000-0002-9676-7032

Yet to confirm: @johnbradley @michael-kotliar @pr80ik @audrium

GitHub Team: https://github.com/orgs/common-workflow-language/teams/tech_team
Matrix Room: https://matrix.to/#/#cwltool-dev:matrix.org

**Comment by DailyDreaming** [comment]
@mr-c I consent to being listed.

**Comment by mr-c** [comment]
> @mr-c I consent to being listed.

Thanks! What is your Matrix username?

**Comment by DailyDreaming** [comment]
@mr-c It is:

```@dailydreaming:matrix.org```

**Comment by DailyDreaming** [comment]
I just joined cwltool-dev.

**Comment by mr-c** [comment]
This is done, except I never heard back from @johnbradley @michael-kotliar @pr80ik @audrium ; you are all still invited to join the CWL Technical Team! Please comment here or send a PR to add yourself to https://github.com/common-workflow-language/cwl-website/blob/main/content/governance.md
