### ISSUE TITLE
User Gallery Nomination: DataPLANT

### ISSUE THREAD

**Issue by ZimmerA** [common-workflow-language/cwl-website#138]
**User or Project name.**
DataPLANT

**Section to list under**
Life Sciences

**Link (URL) to website**
https://nfdi4plants.org/

**Description**
Together with other disciplines, plant research increasingly relying on effective research data management services and infrastructures that facilitate the acquisition, archival, exchange, and processing of research data sets, to enable the exchange of interdisciplinary expertise. While various suggestions on best practices for FAIR data have been made, it is nevertheless always up to individual researchers` initiative and additional effort to adhere to them. Focused on its core mission to minimize the additional work of research data management, DataPLANT wants to support plant researchers in practice, providing technical services and infrastructure and personal support. Therefore, DataPLANT as the [NFDI](https://www.nfdi.de/) (Nationale Forschungsdateninfrastruktur) for plant research, works in a data-centric way and builds on existing structures. A central element for achieving the goal is the [Annotated Research Context](https://nfdi4plants.org/content/learn-more/annotated-research-context.html) (ARC), which acts as single entry point and will define the structure of a future data publication. ARCs are FAIR Digital Objects covering the entire research cycle, from the experiment to the computational aspects to the actual data and metadata, as well as the resulting data publications using existing repositories. The computations that are stored inside an ARC are powered by the Common Workflow Language standards which enable researchers to describe standalone- or delegation workflows. This allows the integration and combination of workflows that were created using various workflow systems and languages while maintaining a uniform metadata description format on the top layer.
Several tools and services are already available to ensure working with ARCs without friction in a collaborative research environment. Accordingly, DataPLANT represents the central point of contact for plant researchers to set up appropriate research data management.

**Logo or small graphic**
https://github.com/nfdi4plants/Branding/blob/master/logos/DataPLANT/DataPLANT_logo_bg_transparent.svg

**Comment by stain** [comment]
Nice! Also added to https://www.researchobject.org/ro-crate/in-use/#dataplant

**Comment by ZimmerA** [comment]
Awesome, thank you!

**Comment by mr-c** [comment]
@ZimmerA if you have the time, you can speed up your entry appearing in the user gallery by following the instructions at https://github.com/common-workflow-language/cwl-website/blob/main/content/EDITING.md#user-galleryyml
