### ISSUE TITLE
Misspelled words on features section of website

### ISSUE THREAD

**Issue by Fienne** [common-workflow-language/cwl-website#147]
The heading "Why Use Workfows" is wrongly spelled on the website.
The word "inherient" on the second line of the second paragraph is wrongly spelled

![Group 1 (4)](https://user-images.githubusercontent.com/72187339/191538069-c5faf771-89d7-4568-8e71-3fce7751de48.png)

The issue can be found [here](https://www.commonwl.org/features/)

**Comment by mr-c** [comment]
Thank you @Fienne !  A fix is coming

**Comment by Fienne** [comment]
You're welcome @mr-c 
I was working on it already

**Comment by Fienne** [comment]
I will certainly do so.
Thank you for the advise!
