### ISSUE TITLE
The drop down menu in the left panel is cluttered

### ISSUE THREAD

**Issue by skanwal** [common-workflow-language/cwl-website#158]
Noted while going through the user guide, the menu on the left panel is cluttered/misaligned.

Adding a screenshot for reference. 

![Screen Shot 2022-11-18 at 11 54 12 am](https://user-images.githubusercontent.com/9857259/202591931-89fcbbbe-b4b1-4c35-ad13-dbb5dda37bf6.png)

**Comment by kinow** [comment]
Hi @skanwal !!

I think that is fixed but no released. Ref issue is https://github.com/common-workflow-language/user_guide/issues/244

The user guide has [a new release process](https://github.com/common-workflow-language/user_guide/blob/main/CONTRIBUTING.md#how-to-contribute) and once others have approve the version with this fix, it should be released and fixed.

Cheers
Bruno

**Comment by skanwal** [comment]
Ah great. Good to know it's being worked on.
Thanks @kinow.
