### ISSUE TITLE
User Gallery Nomination: The NBDC-DDBJ Imputation Server

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/cwl-website#177]
**User or Project name.**
The NBDC-DDBJ Imputation Server

**Section to list under**
Life Sciences

**Link (URL) to website**
https://sc.ddbj.nig.ac.jp/en/advanced_guides/imputation_server/

**Description**
The NBDC-DDBJ Imputation Server enables accurate genotype imputation by leveraging controlled access datasets of the Japanese population. The server is made up of three modules: a workflow execution system, computational workflows specifying the inputs, steps, and outputs of genotype imputation, and a secure web user interface that allows users to specify parameters. Additionally, the server offers reference panels that are ready to use, saving users from having to perform laborious computations on whole-genome sequencing data. With its fully containerized implementation in CWL, the entire system is portable. 

**Logo or small graphic**
[Optional] no logo

We are currently preparing a logo for it.
Can we add a logo after publishing in the User Gallery?

**Comment by mr-c** [comment]
@tom-tan Thank you for this; yes, we can add a logo later! 

Would you mind if we also link directly to the workflows? https://github.com/ddbj/imputation-server-wf

**Comment by tom-tan** [comment]
> Would you mind if we also link directly to the workflows?

No problem!

**Comment by tom-tan** [comment]
Thanks!

**Comment by tom-tan** [comment]
@mr-c Would you move the entry from `Cross-Domain` to `Life Sciences` as described in this issue?
Also, I found that the entries added by #178 are not in the list of `Shortcuts`.
