### ISSUE TITLE
Add a funding page

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#19]
Include information on sponsorship tiers.

**Comment by swzCuroverse** [comment]
@mr-c do you have a write-up somewhere of sponsorship tier info?

**Comment by mr-c** [comment]
The sponsorship tiers proposal is at https://docs.google.com/document/d/1L8bm0gcOrLoYbOHHQCHOOS_xkAu8q9X_WPp2rxqEYOw/edit but it has yet to be approved by the CWL Leadership Team, so skip that for now

Current funding options are: https://github.com/common-workflow-language/governance#donations https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=Z55VS5LBBSZTJ

**Comment by mr-c** [comment]
Thanks!
