### ISSUE TITLE
User Gallery Nomination: The Cherenkov Telescope Array Observatory

### ISSUE THREAD

**Issue by alicefaure** [common-workflow-language/cwl-website#194]
**User or Project name.**
The Cherenkov Telescope Array Observatory

**Section to list under**
Astronomy or Gamma-ray Astronomy 

**Link (URL) to website**
https://www.cta-observatory.org/

**Description**
The Cherenkov Telescope Array Observatory (CTAO) is the next generation observatory for gamma-ray astronomy. It will consist of two arrays of Cherenkov telescopes, spread between two sites: one in the Northern hemisphere in La Palma (Spain), and one in the Southern hemisphere in Paranal (Chile). Currently under construction, CTAO will start scientific operations in the next years for about 30 years. To process observation data and run Monte Carlo simulations to derive the instrument response functions of the telescopes, CTAO has developed a production system prototype. It is based on the [DIRAC](https://dirac.readthedocs.io/en/latest/index.html) framework and manages the workload on a distributed infrastructure. The interface to this production system allows for the configuration and submission of simulation and data processing workflows described in CWL.

**Logo or small graphic**
![image](https://github.com/common-workflow-language/cwl-website/assets/114931215/e8ec901a-4634-4ba8-b62e-4ef5cdab2eb8)

**Comment by alicefaure** [comment]
Thank you for your approval ! However, the logo does not appear on the User gallery. It is just written "The Cherenkov Telescope Array Observatory logo" and the image is absent.

**Comment by mr-c** [comment]
Whoops, sorry about that @alicefaure ! I have [fixed the logo](https://github.com/common-workflow-language/cwl-website/commit/2f313b567703247a3481403dbe3da25099feaf31) and the website is being [rebuilt now](https://github.com/common-workflow-language/cwl-website/actions/runs/7947616891/job/21696665886)

**Comment by alicefaure** [comment]
Thank you very much @mr-c !
