### ISSUE TITLE
list the standing meeting times

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#34]
EMEA-Americas: every Tuesday at 14:30 UTC

APAC: the second Tuesday of every month at 01:00 UTC

**Comment by illusional** [comment]
Yep! This looks good to me :)

**Comment by lunacodes** [comment]
@mr-c where are these supposed to go? Are they links, or just the plain text above?

**Comment by swzCuroverse** [comment]
Do we still need to add this onto the latest CWL draft page?I believe we only have " f you would like to receive Google Calendar invites for the CWL weekly video chat, sign up at https://groups.google.com/g/common-workflow-language-videochat-invites." @tetron or @mr-c  could you follow up with @lunacodes so we can get what you want on the page?

**Comment by mr-c** [comment]
In addition to that I would add:

> Agenda & notes: https://w3id.org/cwl/meeting_minutes
> Previous meeting minutes: [All 2021 meeting minutes](https://drive.google.com/drive/folders/1fVie75MnFiuedz5ImZGX452CA9pB7UEi) + [2021 September - December](https://docs.google.com/document/d/18Eo4qx7oDDOmD1IFlnUcIX0k955gzo6BNoMswxsh9bs/)

> EMEA-Americas CWL meetings are [every Wednesday at 16:00 UTC summer / 17:00 UTC winter](https://arewemeetingyet.com/New%20York/2021-07-21/12:00/w/Weekly%20CWL%20Video%20Chat#eyJ1cmwiOiJodHRwczovL21lZXQuaml0LnNpL0NvbXBldGVudEJyYW5jaGVzTm9taW5hdGVXZWFrbHkifQ==)

There is not an APAC meeting anymore

**Comment by lunacodes** [comment]
@mr-c I'm still confused about what page/location these are supposed to go under

**Comment by mr-c** [comment]
@lunacodes on the community page.

Speaking of which, can you swap all mentions of Gitter for Matrix using  https://matrix.to/#/#common-workflow-language_common-workflow-language:gitter.im  as the target and use the Matrix logo in the header?
