### ISSUE TITLE
clarify the type of workflows CWL is for

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#35]
>  "CWL is for dataflow style batch analysis, where the units of processing are command line programs. " On the https://www.commonwl.org/ page if you added that as the second sentence (after "The Common Workflow Language (CWL) is an open standard...") I think that would make it clear. Something similar could go into the spec with more info, though once you get to a spec you usually know why you are there. But maybe a Scope Statement/Section - "What it is" and "What it isn't" (e.g., "explicitly not for business process modeling") would be helpful there to bound change requests. 

https://gitter.im/common-workflow-language/common-workflow-language?at=5f96dc6c57fe0a4f30359951

https://gitter.im/common-workflow-language/common-workflow-language?at=5f96099beb82301c1a4c348a

**Comment by swzCuroverse** [comment]
This has been done by @lunacodes in the new version of the website.  @mr-c and @lunacodes are you OK with closing this out?

https://deploy-preview-75--cwl-website.netlify.app/features/
