### ISSUE TITLE
Convert CWL website to Jekyll

### ISSUE THREAD

**Issue by lunacodes** [common-workflow-language/cwl-website#37]
Convert [commonwl.org](commonwl.org) to run off [Jekyll](https://jekyllrb.com), in order to facilitate a more straightforward future editing process. This will only affect the main site, and not the user documentation, at present.

- [x] Rewrite site to utilize RWD (Responsive Web Design)
- [x] Evaluate the site's [WCAG Web Accesibility Guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/) compliance and implement any necessary fixes
- [x] Evaluate site performance and implement any necessary improvements
- [x] Incorporate new content
- [x] Add Top Nav Menu and Site Footer
- [x] Setup long-term staging/testing solution 
- [x] Incorporate custom Twitter feed
- [x] Fill in SEO info in _config.yml

**Comment by mr-c** [comment]
Woo-hoo! Thank you @lunacodes !
