### ISSUE TITLE
README needs to explain how this repo works

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#49]
And how to edit the site

**Comment by lunacodes** [comment]
I started a new branch for this - any feedback, requests, etc, is appreciated, and I'll merge it to `add-jekyll-site` when done!

**Comment by mr-c** [comment]
Thank you @lunacodes ; can you open a draft pull request? That makes it a lot easer for me and others to leave comments.

**Comment by lunacodes** [comment]
@mr-c done: https://github.com/common-workflow-language/cwl-website/pull/61
