### ISSUE TITLE
Staging site needs to parse _config_staging.yml 

### ISSUE THREAD

**Issue by lunacodes** [common-workflow-language/cwl-website#55]
The `add-jekyll-site` branch needs to parse both `_config.yml` and `_config_staging.yml`, in order for the staging site to properly function as a staging site. I didn't want to touch the Jenkins build config, but the respective terminal command would be `bundle exec jekyll build --config "_config.yml,_config_staging.yml"`.

This is largely why #54 (incorrect nav links issue) came up.

@tetron @mr-c

**Comment by lunacodes** [comment]
Note: I renamed `_config_local.yml` to `_config_staging.yml` in the most recent push to `add-jekyll-site`

**Comment by tetron** [comment]
Fixed in e76a89f8f882de084769180bebf3ade6cb4592b4 and updated jenkins
