### ISSUE TITLE
Links hrefs to anchors need to use _relative_url

### ISSUE THREAD

**Issue by lunacodes** [common-workflow-language/cwl-website#58]
Link hrefs to anchors need to use `_relative_url` so they work properly, regardless of environment (staging, production, local, etc).

e.g.: `[CWL leadership team]({{ site.url }}/#Leadership_Team)` should be `[CWL leadership team]({{ "#Leadership_Team" | relative_url }})`

**Comment by megha070** [comment]
@lunacodes Are you working on this? If not could you please assign this to me. Would like to take this up.

**Comment by tetron** [comment]
@megha070 thank you for the offer to help, I believe @lunacodes is working on this as part of a larger redesign of the site.
