### ISSUE TITLE
Add page addressing CWL & FAIR principals

### ISSUE THREAD

**Issue by swzCuroverse** [common-workflow-language/cwl-website#60]
Add a page to address how to use CWL with FAIR principals:

https://www.go-fair.org/fair-principles/

Some suggestion topics include:
* RO-Crate ( https://doi.org/10.5281/zenodo.4671709 )
* I believe @mr-c also has a document spelling this out from a more technical perspective he could link here

**Comment by swzCuroverse** [comment]
Working document here in Google Docs:  https://docs.google.com/document/d/12Uj04O5DeT5YeTfTrNCkUak3P-PrevokWpCLhMszbQM/edit?usp=sharing

Everyone should have commenting permission,  I gave editing permission to @mr-c , @stain , @lunacodes and @tetron.  Let me know if you need editing permission.

**Comment by mr-c** [comment]
@swzCuroverse  I dumped my "CWL & the 17 FAIR principles" text in your document

**Comment by swzCuroverse** [comment]
I believe Michael decided this was better served as a blog post or other format than directly on the website.  Can we close this out for now , @mr-c and @lunacodes ?
