### ISSUE TITLE
Mobile Usability issue: Text too small to read

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#63]
Example: https://www.commonwl.org/v1.2/Workflow.html

https://search.google.com/search-console/mobile-usability/drilldown?resource_id=sc-domain%3Acommonwl.org&item_key=CAw&hl=en-DE&sharing_key=9hp-Lpk2kPlWirr-KJFnGg

**Comment by lunacodes** [comment]
Similar to #64 - This is most likely being caused by the body's `font-size: 14px`. On the main site, we fixed it by upping it to `font-size: 0.9375rem` (15px).
