### ISSUE TITLE
Mobile Usability issue: Content wider than screen

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#65]
Example: https://www.commonwl.org/v1.2/Workflow.html

https://search.google.com/search-console/mobile-usability/drilldown?resource_id=sc-domain%3Acommonwl.org&item_key=CAk&hl=en-DE&sharing_key=TDNaQle_OJJgQK833IaDxw

**Comment by lunacodes** [comment]
This is mostly caused by links not having the `word-break` property set in the CSS. It's an easy fix.  It looks like the rest of the issue is being caused by something with the tables.

**Comment by lunacodes** [comment]
@mr-c I can add a stylesheet with the fixes for this, if you want. Just let me know.

**Comment by mr-c** [comment]
> @mr-c I can add a stylesheet with the fixes for this, if you want. Just let me know.

Yes, please!
