### ISSUE TITLE
Remove unused JavaScript

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#67]
URL | Transfer Size | Potential Savings
-- | -- | --
/widgets/widget_iframe.63899b1….html?origin=…(platform.twitter.com) | 103.3 KiB | 99.8 KiB
…js/jquery-3.5.1.min.js(www.commonwl.org) | 31.1 KiB | 21.8 KiB

https://web.dev/unused-javascript/

**Comment by lunacodes** [comment]
I'm pretty sure that Bootstrap actually uses the jQuery - specifically for the mobile menu. I can double-check it next week.

Not really anything we can do about the Twitter script, afaict.

**Comment by lunacodes** [comment]
@mr-c I checked, and Bootstrap does in fact need the jQuery to run. It returns the following error message, if I remove it:

```
Uncaught TypeError: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.
    at Object.jQueryDetection (util.js:179)
    at util.js:195
    at bootstrap.min.js:6
    at bootstrap.min.js:6
```

I'm gonna close this, since both scripts are actually being used.
