### ISSUE TITLE
linkchecker needs to take into account actual root location; add ignore list; and break the build if a link is broken

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#79]
@lunacodes can you open a PR to fix these soonish?
https://github.com/common-workflow-language/common-workflow-language.github.io/blob/21704381d24d5774a12deab9503fc4541c87ea66/linkchecker-report.txt

@tetron can you configure the website build to fail if there are broken links?

**Comment by lunacodes** [comment]
@mr-c I think there's something wrong with the link checker tool. If those things were broken, the entire page would appear really messed up. It appears what's happening is that the tool is not picking up the fact that the file path for all these things is under `/content/`. So it's looking for e.g. `/assets/js/bootstrap.min.js` without understanding that the file path (not url) is actually `/content/assets/js/bootstrap.min.js`. You can verify this sort of thing by opening up your browser's Developer Tools (right click and hit inspect, or else F12 often works) and checking the Console tab. You'll see 404 errors there, if there's an issue.

I ran the site through [brokenlinkcheck.com](https://www.brokenlinkcheck.com/) and [ahrefs.com/broken-link-checker](https://ahrefs.com/broken-link-checker/), which did find one broken link for the homepage (which I'll open a PR for in a few), and a handful for the various doc pages. I'm less familiar with those sections of the site, though I can try to take a look at them, if you want.

Here's the output from the ahrefs.com checker. The left column shows the page containing the broken link; the right column is the actual broken link:

<div class="css-10fhy4c-tableWrapper">
  <div class="css-69sdwe-tableWrapperTable">
    <table class="css-1poo9i3-table css-bkkde6-backlinks">
      <thead>
        <tr>
          <th>
            <div>
              <div><span>Referring page</span></div>
            </div>
          </th>
          <th>
            <div>
              <div><span id="id-f48cdcbf-30c5-4d78-ab78-76947c03926b">Anchor and backlink</span></div>
            </div>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p><a href="https://www.commonwl.org/v1.1/CommandLineTool.html" target="_blank"><span>Common Workflow Language (CWL) Command Line Tool Description, v1.1</span></a></p><a href="https://www.commonwl.org/v1.1/CommandLineTool.html" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/v1.1/CommandLineTool.html</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text">field we recommend their RDF encoding: <a href="https://schema.org/version/latest/schema.rdf" rel="noopener noreferrer">http://schema.org/version/latest/schema.rdf</a> </p><a href="https://schema.org/version/latest/schema.rdf" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">schema.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/version/latest/schema.rdf</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://www.commonwl.org/v1.2/CommandLineTool.html" target="_blank"><span>Common Workflow Language (CWL) Command Line Tool Description, v1.2</span></a></p><a href="https://www.commonwl.org/v1.2/CommandLineTool.html" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/v1.2/CommandLineTool.html</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text">field we recommend their RDF encoding: <a href="https://schema.org/version/latest/schema.rdf" rel="noopener noreferrer">http://schema.org/version/latest/schema.rdf</a> </p><a href="https://schema.org/version/latest/schema.rdf" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">schema.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/version/latest/schema.rdf</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://www.commonwl.org/v1.2/Workflow.html" target="_blank"><span>Common Workflow Language (CWL) Workflow Description, v1.2</span></a></p><a href="https://www.commonwl.org/v1.2/Workflow.html" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/v1.2/Workflow.html</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text">field we recommend their RDF encoding: <a href="https://schema.org/version/latest/schema.rdf" rel="noopener noreferrer">http://schema.org/version/latest/schema.rdf</a> </p><a href="https://schema.org/version/latest/schema.rdf" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">schema.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/version/latest/schema.rdf</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://www.commonwl.org/v1.1/Workflow.html" target="_blank"><span>Common Workflow Language (CWL) Workflow Description, v1.1</span></a></p><a href="https://www.commonwl.org/v1.1/Workflow.html" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/v1.1/Workflow.html</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text">field we recommend their RDF encoding: <a href="https://schema.org/version/latest/schema.rdf" rel="noopener noreferrer">http://schema.org/version/latest/schema.rdf</a> </p><a href="https://schema.org/version/latest/schema.rdf" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">schema.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/version/latest/schema.rdf</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/4700fbee9a5a3271eef8bc9ee595619d0720431b/tests/wf/trick_revsort.cwl" target="_blank"><span>trick_revsort.cwl - Common Workflow Language Viewer</span></a></p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/4700fbee9a5a3271eef8bc9ee595619d0720431b/tests/wf/trick_revsort.cwl" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">view.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/workflows/github.com/common-workflow-language/cwltool/blob/4700fbee9a5a3271eef8bc9ee595619d0720431b/tests/wf/trick_revsort.cwl</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text"> <a href="https://www.iana.org/assignments/media-types/text/plain" rel="noopener noreferrer">File [format]</a> </p><a href="https://www.iana.org/assignments/media-types/text/plain" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.iana.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/assignments/media-types/text/plain</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://view.commonwl.org/workflows/github.com/EOSC-LOFAR/prefactor-cwl/blob/master/prefactor.cwl" target="_blank"><span>prefactor.cwl - Common Workflow Language Viewer</span></a></p><a href="https://view.commonwl.org/workflows/github.com/EOSC-LOFAR/prefactor-cwl/blob/master/prefactor.cwl" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">view.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/workflows/github.com/EOSC-LOFAR/prefactor-cwl/blob/master/prefactor.cwl</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text"> <a href="https://docs.scipy.org/doc/numpy-dev/neps/npy-format.html" rel="noopener noreferrer">File [format]</a> </p><a href="https://docs.scipy.org/doc/numpy-dev/neps/npy-format.html" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">docs.scipy.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/doc/numpy-dev/neps/npy-format.html</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/9f3b9e7b74d5a904b12674dfd1300b56a48c3d33/tests/wf/trick_revsort.cwl" target="_blank"><span>trick_revsort.cwl - Common Workflow Language Viewer</span></a></p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/9f3b9e7b74d5a904b12674dfd1300b56a48c3d33/tests/wf/trick_revsort.cwl" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">view.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/workflows/github.com/common-workflow-language/cwltool/blob/9f3b9e7b74d5a904b12674dfd1300b56a48c3d33/tests/wf/trick_revsort.cwl</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text"> <a href="https://www.iana.org/assignments/media-types/text/plain" rel="noopener noreferrer">File [format]</a> </p><a href="https://www.iana.org/assignments/media-types/text/plain" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.iana.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/assignments/media-types/text/plain</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/eba80916b5cde8bdbd56c077c94240ddf796a27b/tests/wf/trick_revsort.cwl" target="_blank"><span>trick_revsort.cwl - Common Workflow Language Viewer</span></a></p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/eba80916b5cde8bdbd56c077c94240ddf796a27b/tests/wf/trick_revsort.cwl" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">view.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/workflows/github.com/common-workflow-language/cwltool/blob/eba80916b5cde8bdbd56c077c94240ddf796a27b/tests/wf/trick_revsort.cwl</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text"> <a href="https://www.iana.org/assignments/media-types/text/plain" rel="noopener noreferrer">File [format]</a> </p><a href="https://www.iana.org/assignments/media-types/text/plain" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.iana.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/assignments/media-types/text/plain</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/2710cfe731374cf7244116dd7186fc2b6e4af344/tests/wf/revsort.cwl" target="_blank"><span>revsort.cwl - Common Workflow Language Viewer</span></a></p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/2710cfe731374cf7244116dd7186fc2b6e4af344/tests/wf/revsort.cwl" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">view.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/workflows/github.com/common-workflow-language/cwltool/blob/2710cfe731374cf7244116dd7186fc2b6e4af344/tests/wf/revsort.cwl</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text"> <a href="https://www.iana.org/assignments/media-types/text/plain" rel="noopener noreferrer">File [format]</a> </p><a href="https://www.iana.org/assignments/media-types/text/plain" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.iana.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/assignments/media-types/text/plain</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/445f6b3a214f0c48317b25f7af278ae919ce5403/tests/wf/revsort.cwl" target="_blank"><span>revsort.cwl - Common Workflow Language Viewer</span></a></p><a href="https://view.commonwl.org/workflows/github.com/common-workflow-language/cwltool/blob/445f6b3a214f0c48317b25f7af278ae919ce5403/tests/wf/revsort.cwl" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">view.commonwl.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/workflows/github.com/common-workflow-language/cwltool/blob/445f6b3a214f0c48317b25f7af278ae919ce5403/tests/wf/revsort.cwl</span></a>
          </td>
          <td>
            <p class="css-11xn2q0-text"> <a href="https://www.iana.org/assignments/media-types/text/plain" rel="noopener noreferrer">File [format]</a> </p><a href="https://www.iana.org/assignments/media-types/text/plain" target="_blank"><span class="css-w4e3uk-lock"><svg class="css-1g69qe9-iconDirection" height="12px" width="12px" viewBox="0 0 12 12">
                </svg></span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-1wmho6b-fontWeight css-18j1nfb-display">www.iana.org</span><span class="css-a5m6co-text css-p8ym46-fontFamily css-11397xj-fontSize css-18j1nfb-display">/assignments/media-types/text/plain</span></a>
            <div>
              <div>
                <div>404 NOT FOUND</div>
              </div>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

**Comment by lunacodes** [comment]
Broken Link in [Code Libraries](https://www.commonwl.org/#Code_libraries) section of homepage:

Ln. 64 of `_includes/home/software-for-working-with-cwl.html` currently reads:
`|[cwltool](https://github.com/common-workflow-language/cwltool)|cwltool (can be [imported as a Python module](https://www.commonwl.org/(https://github.com/common-workflow-language/cwltool#import-as-a-module)) and [extended to create custom cwl runners](https://github.com/common-workflow-language/cwltool#extension-points)|`

Should read:
`|[cwltool](https://github.com/common-workflow-language/cwltool)|cwltool (can be [imported as a Python module](https://github.com/common-workflow-language/cwltool#import-as-a-module) and [extended to create custom cwl runners](https://github.com/common-workflow-language/cwltool#extension-points)|`

**Comment by mr-c** [comment]
Thanks @lunacodes for the analaysis! @tetron can you configure the linkchecker to take this other root path into consideration?

**Comment by mr-c** [comment]
I fixed the link checker, and some broken links, in https://github.com/common-workflow-language/cwl-website/pull/86
