### ISSUE TITLE
New website changes based on feedback

### ISSUE THREAD

**Issue by swzCuroverse** [common-workflow-language/cwl-website#93]
@tetron had some changes that he suggested that I thought would be good to incorporate into the draft before we get feedback from the larger group.   Maybe @lunacodes can do these?

This is the list, I believe.  @tetron can verify :)

- [x] * Convert both the banner and the boxes on the main page to be clickable links (the whole graphic) instead of having it have a blue hyperlink inside.  The banner should link to the discourse post about the conference: https://cwl.discourse.group/t/2022-cwl-conference-feb-28-mar-4-2022/519
- [x] * Reorder the gallery entries to put the bioinformatics users first,  then the geospatial, hydrology, radio astronomy and general.  Basically this is to keep the most compelling stories first
- [x] * Rename Users Gallery to User Gallery 
- [x] * Make Features a Single Page -- if it looks too large, we could consider adding a left-nav.  Based on what Luna thinks looks best.
- [x] * Move the Background Section from Community to the Features Page.  Instead of naming it about - call it "Benefits of Workflows and Standards"
- [x] * Move the list of Contributors to the About section in their own page.  I believe this is where we landed Peter, but if this is wrong let me know. 
- [x] * Put a maximum width on the text, at least for the text-heavy pages like "Getting Started" or now it would be in Features or About, I believe (added based on Peter's suggestion below)

Additional bug that I added -

- [x] * I can't seem the link to BOSC to work in the timeline, so the hyperlink just needs to be fixed.  Sorry about that.

Thanks @lunacodes.

**Comment by tetron** [comment]
One my major suggestions was to put a maximum width on the text, at least for the text-heavy pages like "Getting started".

**Comment by lunacodes** [comment]
Some additional questions:

>  Convert both the banner and the boxes on the main page to be clickable links (the whole graphic) instead of having it have a blue hyperlink inside. The banner should link to the discourse post about the conference:

For the boxes: currently the title & icon are clickable links. It's tricky to make the entire box clickable, due to the way Jekyll processes markdown & html. But I can make it happen, if the current setup isn't enough.

> Reorder the gallery entries to put the bioinformatics users first, then the geospatial, hydrology, radio astronomy and general. Basically this is to keep the most compelling stories first

Is Bioinformatics the same as the "Life Sciences" section? Is this the correct order?

* Life Sciences
* Geospatial
* Hydrology
* Radio Astronomy 
* Cross-Domain

> Move the Background Section from Community to the Features Page. Instead of naming it about - call it "Benefits of Workflows and Standards"

Just to double-check, you mean the Background Section from Getting Started?

**Comment by swzCuroverse** [comment]
They used to be all on the Governance place - and Michael wanted me to move them to Community which we thought looked odd.

**Comment by lunacodes** [comment]
> Yes, the bordered text section would have a maximum pixel width (maybe ~700px) so if the window is bigger than that, you get margins, but if the window is smaller than that, it uses the full width.

Ok, I'm testing out a few different content area widths. I tried out different max-widths for screens larger than 992px. (We're not necessarily locked into these percentages, I was just sticking with Bootstrap's column system)

11/12 columns (width: 91.66666667%) 
* [Features](https://deploy-preview-75--cwl-website.netlify.app/features/) 
* [Implementations](https://deploy-preview-75--cwl-website.netlify.app/implementations)

10/12 columns (width: 83.33333333%):
* [Specification](https://deploy-preview-75--cwl-website.netlify.app/specification)
* [Community](https://deploy-preview-75--cwl-website.netlify.app/community)

**Comment by tetron** [comment]
I'd consider going even narrower for Specification, what does 9/12 and 8/12 look like?

**Comment by lunacodes** [comment]
@tetron by any chance, could you post a screenshot of what the 10 column looks like for you? To be honest, anything lower than 10 columns seems a bit extreme to me, particularly in contrast to the rest of the site.  

9 Columns:
![spec_9_cols](https://user-images.githubusercontent.com/10420402/153510571-e1596bcf-ff55-4275-8749-78545caaf581.png)

8 Columns:
![spec_8_cols](https://user-images.githubusercontent.com/10420402/153510547-e53ee84b-9d32-41ad-97d2-152c8a9b7c42.png)
.

**Comment by swzCuroverse** [comment]
Yes, I agree.  It looks off to me even if the current setting.  I can make a screen shot.

Some last things:
* Since we move the contributors to their own page - we need to change the link to them on the main page for Vendor Neutrality - and then we can remove the hyperlinked text in the boxes.   Similarly, I think we can to adjust the scale and paralleization links. I think everything else stills go to the correct page but @tetron can verify that for you.

* Thanks you for putting the Gitter feed on the community page,  but after some discussion - we don't think it adds much to the page currently.  Can we remove it?

* For Features can we put the Workflow Blurb's first and then do the parallelization and scale content?  I think it logically flows better that way.  Thank you.   I think also you could merge parallelization and scale into one section and then have the header be red so that everything is parallel in look.  
*

**Comment by swzCuroverse** [comment]
> > One my major suggestions was to put a maximum width on the text, at least for the text-heavy pages like "Getting started".
> 
> @tetron are you saying to make the width of the bordered section here narrower, when it gets closer to the edges?
> 
> ![Screenshot (251)](https://user-images.githubusercontent.com/10420402/153426038-46ad221a-04b9-4c4e-ace7-36dba69e296c.png)
> 
> ![Screenshot (252)](https://user-images.githubusercontent.com/10420402/153426017-7bdbebcd-6f92-47ee-93b6-7a266c245ea8.png)

**Comment by tetron** [comment]
yea, 10 columns is fine

**Comment by lunacodes** [comment]
So with the 10 columns, are we making all the pages on the site (besides the homepage and User Gallery) 10 columns? or just particular pages? If the latter, which ones?

@swzCuroverse some quick questions:

> and then we can remove the hyperlinked text in the boxes. Similarly, I think we can to adjust the scale and paralleization links. 

I'm confused - why are we only removing the hyperlinks for those 3 boxes? Particularly for Vendor Neutrality, since the two links go to different places (one to Participating Organizations, and one to Individual Contributors)

> When you were moving around the gallery entries - [US Food and Drug Administration (FDA) somehow got lost from the first entry.

This seems to be a bug in the template code. Hoping to have it worked out later today.

> For Features can we put the Workflow Blurb's first and then do the parallelization and scale content?

So will the new page structure look like this?

* Reusability and Reproduciblity with CWL
* Parallelization and Scale
* Benefits of Workflows and Standards
	* Why Use Workfows?
	* Why Use a Standard?
	* When to Use CWL?

**Comment by swzCuroverse** [comment]
* We should remove them for all the boxes -- that was poor wording.   For vendor neutrality - both those links now are on the Contributors page so I think if I icon and box label goes there that would be fine. 

* Yes, FDA looks good now

* This would be my preferred order:
* 
    Benefits of Workflows and Standards
        Why Use Workfows?
        Why Use a Standard?
        When to Use CWL?
    Reusability and Reproduciblity with CWL
    Parallelization and Scale with CWL 

Thanks!

**Comment by lunacodes** [comment]
I finished up all the changes, but still need to figure out the User Gallery bug,

10 columns: I changed Specification and Features to the 10 column layout. Are there other pages that should use it, or is that it?

Also I noticed that `governance.md` contains `CWL is a member project of the Software Freedom Conservancy. In general, [discussions about CWL should happen on open forums](https://www.commonwl.org/#Support)` - but that section doesn't exist on the new site, nor does the content I see there. Not sure what to do with this?

**Comment by swzCuroverse** [comment]
Thanks Luna - so I think that should probably go to ---> https://deploy-preview-75--cwl-website.netlify.app/community/

@tetron any other pages need this?

Also - I noticed there is something funky with the ep3 badge here, I think @mr-c fixed in the live version of the old cwl site.  https://deploy-preview-75--cwl-website.netlify.app/implementations/

**Comment by swzCuroverse** [comment]
Parallelization and Scale [§](https://deploy-preview-75--cwl-website.netlify.app/features/#parallelization-and-scale)  --- should probably say Parallelization and Scale with CWL and be in red to have it look like the Reusability and Reproduciblity with CWL header.

**Comment by mr-c** [comment]
The following implementations can be removed from the list: Consonance, AWE, yacle, Cromwell, CWLexec

**Comment by lunacodes** [comment]
I made the rest of the changes. As for the columns:

> I person think it looks odd to have some pages with it and some without and have the header text jump around, but maybe that is just me?

I agree. Though, it looked weirder to leave the header text in its original place.

![Specification - with original header text position](https://user-images.githubusercontent.com/10420402/153734265-2ed8a265-5cf4-497e-83af-a6208f0ad8d4.png)
<br>
One possibility would be moving everything to 10 columns. Here's what that would look like, for some of the pages:

![10 cols - Getting Started](https://user-images.githubusercontent.com/10420402/153734360-f3dbebad-30b9-4534-a39a-9f150a099ad7.png)

![10 cols - Timeline](https://user-images.githubusercontent.com/10420402/153734758-c9b0d9e7-ffb0-415f-99b0-6a47e8ded453.png)

![10 cols - About](https://user-images.githubusercontent.com/10420402/153734355-d136f49f-8d2d-4e5f-8910-ec18a0468eae.png)

![10 cols - Community](https://user-images.githubusercontent.com/10420402/153734357-2e972a07-6672-4ad9-93f6-ca22c9efa5e3.png)

![10 cols - Donate](https://user-images.githubusercontent.com/10420402/153734359-7c35827a-0bc4-4ec1-8ea6-3498c58c0306.png)

Getting started looks a little weird to me, but that's due to the shorter content.

**Comment by swzCuroverse** [comment]
@lunacodes  -- I am torn but I guess let's try 10 and see what people link?  Also, I think the last outstanding thing is the FDA issue, or did that get fixed?  @tetron once Luna is done with this last fix - I think we can declare the new website ready for review for the leadership team.

**Comment by swzCuroverse** [comment]
Oh Sorry - one more small this is the link the DNA Nexus seems now to be now formatted correctly [DNAnexus](https://www.dnanexus.com/ -->  In the implementations section.  I think that is it :)

**Comment by lunacodes** [comment]
Ok I'll give the 10 columns a try. 

The FDA issue still needs to be worked out. I'll take a look at the Implementations entry when I have a moment.

**Comment by swzCuroverse** [comment]
Thanks Luna - if you can't figure it out in a few days- we can always send it out for review with a note saying that is going to be resolved.

**Comment by tetron** [comment]
I made a pass over it, I'll send out a note saying it is ready to review tomorrow morning.

**Comment by lunacodes** [comment]
Awesome. Fixed the FDA Bug :)

**Comment by swzCuroverse** [comment]
I don't know if this is a function of the new indenting but the top navigation seems to move and be located in a slightly different place for some of the different pages.   For Example if I go from User Gallery and Getting Started the top nav entries move.

**Comment by lunacodes** [comment]
@swzCuroverse I noticed that. It's a result of the new indenting. I'm working on fixing it up tonight

**Comment by lunacodes** [comment]
I misspoke earlier, the nav positioning is actually due to the lack of a scrollbar on the pages with short content. Additionally, with the new indentations, the content area was also shifting. As far as I can tell, both of these were an issue on Chrome & Firefox specifically, and should now be fixed.

**Comment by geoffjentry** [comment]
👍

**Comment by hmenager** [comment]
Great work, thumbs up!

Minor typo, "Portablity->Portability" [here](https://github.com/common-workflow-language/cwl-website/blame/new-site/content/features.md#L37)

**Comment by lunacodes** [comment]
@hmenager thanks for catching the typo!

@suryasaha thanks - that's a function of the staging site. It works properly, when it's deployed.

**Comment by bdusenbery** [comment]
Looks great! Good to go from me.

**Comment by stain** [comment]
Thanks for this wonderful work, and glad to see this deployed!
