### ISSUE TITLE
new notable user: ACROSS

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-website#96]
name: The ACROSS European Project
logo: https://www.acrossproject.eu/wp/wp-content/uploads/2021/03/ACROSS_Logo_107x28.jpg
website: https://www.acrossproject.eu/
section: Cross-Domain

(via https://github.com/common-workflow-language/common-workflow-language/wiki/Notable-CWL-mentions%2C-adoption%2C-and-users/#the-across-european-project )

**Comment by swzCuroverse** [comment]
We need a description.

**Comment by mr-c** [comment]
The ACROSS project is an European High-Performance Computing Joint Undertaking that will co-design and develop an HPC, BD, and Artificial Intelligence (AI) convergent platform, supporting applications in the **Aeronautics**, **Climate and Weather**, and **Energy** domains. The project will leverage effective mechanisms to easily describe and manage complex workflows and monitoring running systems and applying smart mechanisms of scheduling jobs

**Comment by lunacodes** [comment]
Added

**Comment by GlassOfWhiskey** [comment]
Hello,
It is fine to point at the CORDIS site throug the G.A. number, but could you point to the official ACROSS website from the first link?
I mean, substituting

[HPC Big Data Artificial Intelligence Cross Stack Platform Towards Exascale](https://cordis.europa.eu/project/id/955648)

with

[HPC Big Data Artificial Intelligence Cross Stack Platform Towards Exascale](https://www.acrossproject.eu/)
